nelmio_api_doc:
    documentation:
        info:
            title: DualMedia Recruitment Task
            description: by Witold Karaś (witold.karas00@gmail.com)
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /